/**********************************************************************

  Tenacity

  ThemePackage.h

  Avery King

  License: GPL v2 or later

**********************************************************************/

#include "ThemeResourceList.h"

const std::list<std::string> KnownThemeResourceNames
{
    // Colors /////////////////////////////////////////////////////////////////
    "blank",
    "unselected",
    "selected",
    "sample",
    "selSample",
    "dragSample",
    "muteSample",
    "rms",
    "muteRms",
    "shadow",
    "aboutBackground",
    "trackPanelText",
    "labelTrackText",
    "meterPeak",
    "meterDisabledPen",
    "meterDisabledBrush",
    "meterInputPen",
    "meterInputBrush",
    "meterInputRMSBrush",
    "meterInputClipBrush",
    "meterInputLightPen",
    "meterInputDarkPen",
    "meterOutputPen",
    "meterOutputBrush",
    "meterOutputRMSBrush",
    "meterOutputClipBrush",
    "meterOutputLightPenl",
    "meterOutputDarkPen",
    "rulerBackground",
    "axisLines",
    "graphLines",
    "ResponseLines",
    "hzPlot",
    "wavelengthPlot",
    "envelope",
    "muteButtonActive",
    "muteButtonVetoed",
    "cursorPen",
    "recordingPen",
    "playbackPen",
    "recordingBrush",
    "playbackBrush",
    "rulerRecordingBrush",
    "rulerRecordingPen",
    "rulerPlaybackPen",
    "timeFont",
    "timeBack",
    "timeFontFocus",
    "timeBackFocus",
    "labelTextNormalBrush",
    "labelTextEditBrush",
    "labelUnselectedBrush",
    "labelSelectedBrush",
    "labelUnselectedPen",
    "labelSelectedPen",
    "labelSurroundPen",
    "trackFocus0",
    "trackFocus1",
    "trackFocus2",
    "snapGuide",
    "trackInfo",
    "trackInfoSelected",
    "light",
    "medium",
    "dark",
    "lightSelected",
    "mediumSelected",
    "darkSelected",
    "clipped",
    "muteClipped",
    "progressDone",
    "progressNotYet",
    "syncLockSe",
    "selTranslucent",
    "blankSelected",
    "sliderLight",
    "sliderMain",
    "sliderDark",
    "trackBackground",
    "placeHolder1",
    "graphLabels",
    "spectroBackground",
    "scrubRuler",
    "timeHours",
    "focusBox",
    "trackNameText",
    "midiZebra",
    "midiLines",
    "textNegativeNumbers",
    "clipAffordanceOutlinePen",
    "clipAffordanceInactiveBrush",
    "clipAffordanceActiveBrush",
    "clipAffordanceStroke",
    "ipLabelTrackTextSelection",
    "ipNameText",
    "ipNameTextSelection",

    // Bitmaps ////////////////////////////////////////////////////////////////
    "pause",
    "pauseDisabled",
    "play",
    "playDisabled",
    "loop",
    "loopDisabled",
    "cutPreview",
    "cutPreviewDisabled",
    "stop",
    "stopDisabled",
    "rewind",
    "rewindDisabled",
    "ffwd",
    "ffwdDisabled",
    "record",
    "recordDisabled",
    "recordBeside",
    "recordBesideDisabled",
    "recordBelow",
    "recordBelowDisabled",
    "scrub",
    "scrubDisabled",
    "seek",
    "seekDisabled",

    // Tool icons
    "IBeam",
    "zoom",
    "envelope",
    "timeShift",
    "draw",
    "multi",
    "mic",
    "speaker",

    // Zoom
    "zoomFit",
    "zoomFitDisabled",
    "zoomIn",
    "zoomInDisabled",
    "zoomOut",
    "zoomOutDisabled",
    "zoomSel",
    "zoomSelDisabled",
    "zoomToggle",
    "zoomToggleDisabled",

    // Edit actions
    "cut",
    "cutDisabled",
    "copy",
    "copyDisabled",
    "paste",
    "pasteDisabled",
    "trim",
    "trimDisabled",
    "silence",
    "silenceDisabled",
    "undo",
    "undoDisabled",
    "redo",
    "redoDisabled",

    #ifdef EXPERIMENTAL_VOICE_DETECTION
    "tnStartOn",
    "tnStartOnDisabled",
    "tnStartOff",
    "tnStartOffDisabled",
    "tnEndOn",
    "tnEndOnDisabled",
    "tnEndOff",
    "tnEndOffDisabled",
    "tnCalibrate",
    "tnCalibrateDisabled",
    "tnAutomateSelection",
    "tnAutomateSelectionDisabled",
    "tnMakeTag",
    "tnMakeTagDisabled",
    "tnSelectSound",
    "tnSelectSoundDisabled",
    "tnSelectSilence",
    "tnSelectSilenceDisabled",
    #endif

    // Sync Lock
    "syncLockSelected",
    "syncLockTracksDown",
    "syncLockTracksUp",
    "syncLockTracksDisabled",
    "syncLockIcon",

    // Label Glyphs
    "labelGlyphLeft",
    "labelGlyphLeftSelected1",
    "labelGlyphLeftSelected2",
    "labelGlyphRight",
    "labelGlyphRightSelected1",
    "labelGlyphRightSelected2",
    "labelGlyphSingle",
    "labelGlyphSingleSelected",
    "labelGlyphSingleLeftSelected",
    "labelGlyphSingleRightSelected",

    // Play and Thumb Heads

    "playPointer",
    "playPointerPinned",
    "recordPointer",
    "recordPointerPinned",
    "grabberDropLoc",
    "sliderThumb",
    "sliderThumbHilited",
    "sliderThumbRotated",
    "sliderThumbRotatedHilited",

    // Track Panel Buttons
    "upButtonExpand",
    "upButtonExpandSel",
    "downButtonExpand",
    "downButtonExpandSel",
    "hiliteUpButtonExpand",
    "hiliteUpButtonExpandSel",
    "hiliteButtonExpand",
    "hiliteButtonExpandSel",

    // Toolbar Buttons
    "upButtonLarge",
    "upButtonSmall",
    "downButtonLarge",
    "downButtonSmall",
    "hiliteUpButtonLarge",
    "hiliteUpButtonSmall",
    "hiliteButtonLarge",
    "hiliteButtonSmall",
    "toggleScrubRuler"
};
